### ISSUE TITLE
Error: Call to a member function file_get_contents() on null in...

### ISSUE THREAD

**Issue by MaxG-Git** [matiasdelellis/facerecognition#295]
Hey! Fair warning im a bit of a newbie so apologies if some of this is obvoius or what not but I really cannot seem to figure it out.

### Expected behaviour

Face Scan skips corupted or broken images

### Actual behaviour

Face Scan crashes when scanning corupted image, stops process

### Steps to reproduce
1. Install Manually (followed process on wiki titles "Hard method"
2. Run Background Scan (on folder that contains corupted images)
3.Wait for known corrupted image to be processed and scan crashes

### Server configuration

Binary Nextcloud Instalation, 

* **Operating system:**
Ubuntu 19.0.4 - 16GB Ram

* **PHP version:**
7.3.11 - 4G Ram Limit

* **Web server:**
Nginx

* **Database:**
Mariadb

* **Nextcloud version:**
Nextcloud 18.0.6

### Longer Description
After setting up the app by following the intructions, I was able to run a background job using the occ face:background_job. which found 24000+ photos. The scan started perfectly and ran for about 2 hours recognizing faces perfectly. After around 2 hours I noticed the process had stopped. The nextcloud settings panel for the app has the text `Analyzing images - 24478 images detected - 19689 images in queue - Ends approximately in 14 hours`  and is stuck on that number. The logs say give me the following error:
```
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /usr/share/nginx/nextcloud/lib/private/Files/Filesystem.php:712
Stack trace:
#0 /usr/share/nginx/nextcloud/lib/private/legacy/image.php(621): OC\Files\Filesystem::file_get_contents('/usr/share/ngin...')
#1 /usr/share/nginx/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile('/usr/share/ngin...')
...
```

After the crash I looked at the personal settings page for the app and saw that: for the files that sucessfuly scanned (within that 2 hour period), everything was sorted correctly.

I tried resuming the scan by re running the command but within about 6-7 photos scanned it hits another "corupted" image and fails.

### Some things I've Noticed:
* The scan fails when reading a file that has a (`a number`) at the end of the name ex: `imageName(1).jpg' - Im not sure if this has anything to do with it but this seems to be concistent 

* The files that cause it to fail **are** corupted images, I have a lot of corupted files in a spesific folder alongside other photos I would like to scan I was hoping the corupted files would be skipped. - I have tried to create a file with the name `.nomedia` in the folder with these corupted images to just skip them and deal with this later but when I re-run the occ background job command again it resumes the scan, it still scans for photos in that folder.

I feel like I may be missing something obvoius or am doing something wrong, If so please lmk 😄

**Comment by MaxG-Git** [comment]
### Update: 
It seems the files that are failing are: files created by android "Motion Photo" mode (more details on this file type [here](https://android.jlelse.eu/working-with-motion-photos-da0aa49b50c))

In this mode the device takes two photos one normal jpg and one of these special photo types. The special photo types is the one that crashes the scan

**Comment by matiasdelellis** [comment]
Hi @MaxG-Git 

Wow..
Thank you very much for the report. Your research is very complete. :smiley: 

> The scan fails when reading a file that has a (a number) at the end of the name ex: imageName(1).jpg - Im not sure if this has anything to do with it but this seems to be concistent

It seems strange, but probably never tested it.

> It seems the files that are failing are: files created by android "Motion Photo" mode (more details on this file type here)

Ohh.. In principle, as you say they look corrupt because Nextcloud has no support for them. If you want to analyze the file, we need support to open these files in Nextcloud. 

The only report I found on Nextcloud is this:
* https://github.com/nextcloud/photos/issues/365

... although I think it's more of a https://github.com/nextcloud/server problem.

On the other hand, on our part, the only thing we can do is ignore the error, since we could not detect the type of file until we have the error. :disappointed: 

Finally, please confirm that the file: `/usr/share/ngin...` (You can see the complete file in real log) exists.. and if you can attach a test file for testing we can help you better.

Thanks again.

**Comment by MaxG-Git** [comment]
Hi! Thank you for the super fast responce 😄 
I really appriciate the help!

Just have a couple of questions :) Regarding:

> Finally, please confirm that the file: /usr/share/ngin... (You can see the complete file in real log) exists.. and if you can attach a test file for testing we can help you better.

Are you talking about the corupted image (or now known as the "motion image") itself when saying `/usr/share/ngin...` ?

If so, yes it does exisit and can be found [here](http://link.maxg.cloud/facerecognitionissues295) 
If not, what file are you talking about?

Thanks again for the help it is much appriciated! 😃

**Comment by matiasdelellis** [comment]
Hi @MaxG-Git 

Beyond that we have to improve something, it seems that you tried to extract the videos, but they these left with the wrong extension. :sweat_smile:

According to your link, how are the videos extracted?
```
[matias@ideapad Shared]$ exiv2 -px MVIMG_20180925_183436.jpg 
Xmp.GCamera.MicroVideo                       XmpText     1  1
Xmp.GCamera.MicroVideoVersion                XmpText     1  1
Xmp.GCamera.MicroVideoOffset                 XmpText     7  3936110
Xmp.GCamera.MicroVideoPresentationTimestampUs XmpText     6  752441
[matias@ideapad Shared]$ ls -la MVIMG_20180925_183436.jpg 
-rw-rw-r--. 1 matias matias 7504412 jul 15 13:04 MVIMG_20180925_183436.jpg
[matias@ideapad Shared]$ echo '7504412-3936110' | bc
3568302
[matias@ideapad Shared]$ dd if=MVIMG_20180925_183436.jpg of=video.mp4 bs=3568302 skip=1
1+1 registros leídos
1+1 registros escritos
3936110 bytes (3,9 MB, 3,8 MiB) copied, 0,00957202 s, 411 MB/s
[matias@ideapad Shared]$
```

You can verify that these are the same files. :sweat_smile: 
```
[matias@ideapad Shared]$ md5sum MVIMG_20180925_183436\(1\).jpg 
cb81946f3e9eb8eb135fd545bb2c633d  MVIMG_20180925_183436(1).jpg
[matias@ideapad Shared]$ md5sum video.mp4 
cb81946f3e9eb8eb135fd545bb2c633d  video.mp4
```

So, just remame the file `MVIMG_20180925_183436(1).jpg` to MVIMG_20180925_183436.mp4 and enjoy your videos ... :grimacing:

**Comment by MaxG-Git** [comment]
Hey! Thanks again for the fast responce! 😄 👍 
I changed the name of that particular file and it did exatly as you said; turning into a proper `.mp4`
I now know: 
* what is causing the error - _The file type is unrecognizable_
*  a way to fix these files (individually) - _Change file type to mp4_

Because of this I feel this issue could at this point be classified as "solved" I appriciate the help and the awesome app!

#### Continuation...

I seem to have a lot of these "wrong file type" mp4's in a spesific folder, one aditinal question is:  Could I skip scanning this parent folder entirley thus not scanning any of these files? I seem to be having trouble with creating a `.nomedia` file to get it not to scan. Could this possibly because I am not restarting the scan and instead resuming the scan?

Other than that I think I may have to find a way to automate the conversion of these files as I have **a lot**, in different direcotries (within a spesific parent folder). But like I said prevously I feel that this is beyong the scope of this issue ticket - but for those who may have a similar issue, if I (or anyone else) figure an easy way to automate this process I can link it to help other newbies like me 😄 .

**Comment by matiasdelellis** [comment]
> Because of this I feel this issue could at this point be classified as "solved"

The problem is that Nextcloud makes a lot of decisions based on the file extension (More than anything for performance). I would still like to add something to avoid these errors, but I'll think about it later.

> I appriciate the help and the awesome app!

Thank to you!. :smile: 

> I seem to have a lot of these "wrong file type" mp4's in a spesific folder, one aditinal question is: Could I skip scanning this parent folder entirley thus not scanning any of these files?

You can deactivate a particular folder (and all its children), with the side panel..

![Captura 2020-07-15 14 22 49](https://user-images.githubusercontent.com/733715/87575718-b282aa80-c6a6-11ea-8c00-8c2265fd62d2.png)

> I seem to be having trouble with creating a .nomedia file to get it not to scan. Could this possibly because I am not restarting the scan and instead resuming the scan?

The `.nomedia` file should also work. Either option activates a flag asking to the background_job process to check the files list, and delete the files that were disabled or are no longer available.

**Comment by MaxG-Git** [comment]
Perfect Thank you 😄 

### If you are expriencing same issue:

I have created (using a guide found: [here](https://mywiki.wooledge.org/BashFAQ/030)) a simple simple bash file that will change all files starting with `MVIMG` and end with `(1)` from a `jpg` to a `mp4`. In my case this has solved the problem and I can now resume scanning! 

**Beware!** This worked for my spesific scenario and may not work for you. This bash file **WILL** rename data in your data folder! **Use at own risk!!**

### How I did this

**Comment by MaxG-Git** [comment]
Perfect Thank you 😄 I doubt anyone will have this exact issue but....

### If you are expriencing same issue:
I have created (using a guide found: here) a simple simple bash file that will change all files starting with MVIMG and end with (1) from a `jpg` to a `mp4`. In my case this has solved the problem and I can now resume scanning!

Beware! before continuing please note: This worked for my spesific scenario and may not work for you. This bash file WILL change the extension of any file with both `MVIMG` at the start and `(1).jpg` at the end in your data folder! Use at own risk!!

### How I did this:

Change current director to nextcloud folder (change `/path/to/nextcloud/` to your nextcloud root folder. The rest of the commands will be run in this directory so do not "cd" out of ths directory
```
cd /path/to/nextcloud/
```

Use your favourite editor to create a file. I will be creating a file with `nano` and naming it `fixMP4.sh` but you can choose any name for the file
```
sudo nano fixMP4.sh
```

You should now see the new `.sh` file open to write too. Use the follwing code to copy into this new file. Then save and close the file
```
#!/bin/bash
sudo find . -name 'MVIMG*(1).jpg' -print0 | while IFS= read -r -d '' f; do
  mv -- "$f" "${f%.jpg}.mp4"
done
```
> The following code, when executed will look in the current directory (the one the file is currently sitting in, for this case it will look in the  `nextcloud` folder) and replace any file with the begining of `MVIMG` and ending `(1).jpg` to an mp4.


Once the file is saved, change the file from a normal text file to an executable by running the following command (Note: If your `.sh` file is named differently change the filename in this command respectivley)
```
sudo chmod +x fixMP4.sh
```

Once complete your file is now an executable file. 

Beyond this point we are going to make changes to the data so a backup of your files is suggested as **there is no going back after this point**

To run the executable (and subseuently change the file exentions) run the bash script. (Note: If your `.sh` file is named differently change the filename in the command respectivley)
```
sudo bash fixMP4.sh
```
Next to record the changes in your nextcloud file structure database use nextcloud file scan command. If your broken mp4's are in a spesific folder you can add a path with `-path=" /path/to/directory"` to avoid scanning all your files
```
sudo -u www-data php occ files:scan 
```
> Depending on how many files you have this may take a while

And that should be it! 😄  your files are now proper mp4's!  You can continue on with your face scans without crashing!

~ Thank you so much for the help @matiasdelellis would not have been able to figure what to do without your help! 😄 Happy Coding!

**Comment by strugee** [comment]
@matiasdelellis been meaning to report this for a long time now and I've been too lazy. Kudos for @MaxG-Git for beating me to it :P

I _did_ look into this a while ago and found the nextcloud/server issue that you found, plus a few others in miscellaneous apps. The general consensus seems to be to just silently swallow this error.

@MaxG-Git I know you already solved your problem but just for future reference, you can do it a little more elegantly (at least, IMHO):

    $ file * | grep JPEG | cut -d: -f1 | rename -d 's/.[[:alnum:]]+$/.jpg/'

This requires `rename` to be installed, of course. It is also slow(er) because `file` interrogates the contents of files, but that means it will work on any file extension which is nice. It should be more than fine for a one-off job unless you have a million files or your disk is totally dead or something like that.

That will break if your filenames contain `:` or newlines or the string `MP4` though. Here's a version that (I think) doesn't:

    $ find . -type f -exec sh -c 'file -b "{}" | grep -q MP4' ';' -print0 | rename -0 -d 's/.[[:alnum:]]+$/.mp4/'

Tack `-n` onto the end to tell `rename` to do a dry-run first, so you can sanity-check the results. This works by telling `find` to run a test on each file it encounters: the test to be run is `sh -c 'file -b "{}" | grep -q MP4'` (`sh -c` because we need `|`). `file -b` does not output the filename, which eliminates our naming problem, and `grep -q` suppresses output and instead only returns an exit code. Since `grep` returns 0 if it finds a match and 1 if it doesn't, the `find` test evaluates to true if `file` says the file is a MP4, false otherwise. We then tell `find` to print null-delimited filenames (once again sidestepping the newline-in-filename problem), which `rename -0` happily reads from stdin. (This solution is probably littered with GNU extensions but we were already using `-print0` anyway so who cares.)

If you have a Nextcloud folder on a client machine (or can mount it somewhere over WebDAV) you could run it there and let the client sync the changes to the server. That way you can skip the rescan step and your changes will be properly recorded in the activities UI. Hope this is at least somewhat interesting/helpful :-)

**Comment by Derkades** [comment]
It would indeed be nice if the scanner continued if it encountered an error processing files. I have a couple of motion pictures and the background job keeps failing because of it. In the future, being able to recognise faces in these files would be ideal but for now not crashing is good enough.

**Comment by strugee** [comment]
@Derkades what does `file` report if you run it on one of those files? And what's the filename?

**Comment by Derkades** [comment]
I guess it was a false alarm, I got the error every cronjob for days in a row but it disappeared. Maybe a missing file that was finally re-scanned? Still, if a file is missing it should skip that file instead of crashing entirely.

**Comment by matiasdelellis** [comment]
Hi all!.

Actually, there is already a routine that captures the errors, and elegantly saves them in the database. This particular error fails, because it is not a simple exception. I could try to fix it again.

**Comment by matiasdelellis** [comment]
Well..
Checking again, it is an error that could be recovered, but ideally it should be fixed in Nextcloud. 

You have to follow it on https://github.com/nextcloud/server/issues/7276

**Comment by ntimo** [comment]
Hey, I just started using the app and I also run into this error. Did you made any progress on a wrapper? So that the analysis can continue if a file is broken?

**Comment by strugee** [comment]
@ntimo personally I just put it in an infinite loop in the shell. That probably won't work so well when the analysis is done though...

**Comment by ntimo** [comment]
@strugee I am running the cronjob every two minutes with a timeout of 110 seconds :D But thats still not an elegant solution.

**Comment by matiasdelellis** [comment]
Hi @ntimo 
Although I recognize that it is not ideal, the entire task is designed to work progressively. If it fails, it is a problem, but you should always run it continuously..

The application has the ability to capture errors, and mark the file as corrupt:

For example this is my database:

id | user | file | model | is_processed | error | last_processed_time | processing_duration
-- | -- | -- | -- | -- | -- | -- | --
245285 | matias | 193323 | 4 | 1 | Image is not valid, probably cannot be loaded | 2020-09-09 00:53:28 | 0
249993 | matias | 215811 | 4 | 1 | Image is not valid, probably cannot be loaded | 2020-09-09 00:54:01 | 0
251369 | matias | 202097 | 4 | 1 | Image is not valid, probably cannot be loaded | 2020-09-09 00:54:50 | 0

...but there are error that I can't capture properly and in general these errors need to be fixed in nextcloud/server#7276

If you really have so many malformed files, I would recommend that you review it properly.

Sorry, I don't have a better answer .. :disappointed:

**Comment by strugee** [comment]
> @strugee I am running the cronjob every two minutes with a timeout of 110 seconds :D But thats still not an elegant solution.

Just to add on to what @matiasdelellis said, if you run it this way you're taking a big perf hit: if you have a non-trivial number of images to process, you're going to process some images in the 2 minute time frame, get killed, then start up and run clustering. You'll process a few more images in the remaining time, get killed, then start again and run clustering _again_. Etc. You're wasting CPU time running clustering when you're just going to have to run it again (and then again, and again...) after you process a few more images.

From your description, it seems like you're basically trying to stop multiple cronjobs from running at the same time and trampling on each other. If that's correct, I would suggest using a lockfile. Here's an example crontab entry, although this one is for the previewgenerator app and not this app (you can just adjust the command though; it's the same principle):

```
# See also /etc/tmpfiles.d/nextcloud-lock.conf
# We allow infinite retries because otherwise dotlockfile(1) errors out when it can't get the lockfile
# This is okay because when this command has no work, it returns very quickly. So we basically end up with a large queue of noops competing for the lock.
# This queue will be drained extremely quickly.
*/1  *  * * *   www-data    dotlockfile -p -r -1 /var/run/nextcloud/previewgenerator.lock php -f /srv/http/nextcloud/occ preview:pre-generate
```

and here's the referenced `systemd-tmpfiles(8)` file:

```
#Type Path            Mode UID      GID      Age Argument
d     /run/nextcloud  0755 www-data www-data -   -
```

Note though that the above comment's logic assumes that it will not take, say, weeks to completely empty the queue of images to process (feel free to not read this paragraph if you're not interested in why :joy:). Say I upload enough images at once for a previewgenerator run to take a week. There are 10080 minutes in a week, so I will end up with 10079 no-op processes. The biggest problem with this number is that you've blown _well_ past the default limit of process identifiers on the system (see `sysctl kernel.pid_max`, assuming you're running Linux), so nothing will be able to spawn new processes unless you increase this value (which will probably itself require starting a process, so you'll probably be forced to reboot). If you're running on a relatively CPU-constrained system (or at least, a system that's CPU-constrained while facial recognition is running) you _might_ also run into CPU contention problems with thousands of `dotlockfile` processes testing whether the lockfile still exists, though that's still a trivial operation so probably not.

(Also, just to clarify, when I talked about running the job in an infinite loop, the reason I do that is because that basically lets the app swallow errors and keep processing - errors most commonly being this bug, or the app being killed because an image used too much memory. The advantage of doing it this way is that I get to deal with the files that cause errors all at one time at the end, instead of constantly checking whether I need to manually restart the program because it crashed. This is useful for me because with my setup it takes over a month to fully process all my uploads, and if I put it on a cronjob it would definitely trigger the above problem as well as several others.)

**Comment by ntimo** [comment]
@strugee you are absolutely correct that is was a dumb idea. In the end I used a bash script to run the processor in a infinite loop with a timeout of 15 minutes. And placed a few .nomedia files in my nextcloud (for example in folders that contain background images and screenshots). The problem then also never reoccured. Seems like on of my screenshots or background images is a bit broken. Have to check that once I find time. And yes indeed using lock files is a pretty good idea 👍

**Comment by lftsy** [comment]
Good morning, I did cope with the same problem

* **Information**: I have a lot of pictures and over time with a lot of nextcloud encryption tests/rollback and sync, I had some pictures that were corrupted. 
ex : 
./DSC03233.JPG: ASCII text, with very long lines, with no line terminators
./DSC03222.JPG: ASCII text, with very long lines, with no line terminators

* **Problem**: If the face:background_job start to scan one of these pictures, it crashes with the error "file_get_contents() on null"

* **Workaround**: I have used this command to find all corrupted pictures and remove them
find . -type f -exec file {} \; | grep "ASCII" | cut -d":" -f 1 | sed "s/^\(.*\)$/rm \"\1\"/"
rm "./2003/10 - Invitation/823.jpg"
rm "./2003/10 - Invitation/412.jpg"
rm "./2003/10 - Invitation/620.jpg"

then audit the list and paste the rm commands

* **Solution**: I think that when the face:background_job cope with an invalid file, it should skip it and try to analyse the next one

* Steps To Reproduce
1) Create a .jpg file with the content of a text file "ASCII text, with very long lines, with no line terminators"
2) Upload it in your cloud
3) Start the face:background_job on it

Questions
1) Would it be hard to ask the face:background_job to skip an invalid file and start analysing the next file ?

Thanks and Best Regards
Marc

**Comment by isaacolsen94** [comment]
I believe that the .nomedia or button to specify NOT to scan a directory doesn't work if you enable to  "Group Folders" option. I have a group folder and I moved all the "MVIMG..." files into it and added .nomedia as well as verified the check mark is not marked but the background_job still scans the directory. Pictured below:
![image](https://user-images.githubusercontent.com/52682311/131890799-df037c93-f3cf-4afe-8119-c8bd315e040d.png)

**Comment by joshtrichards** [comment]
This should no longer be the case today. I suspect this can be closed.
